// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUyutJoul2QINEC3I4moxQDMc2v2vmLG4',
    appId: '1:1098018897892:web:18769e6589a1983b7751f1',
    messagingSenderId: '1098018897892',
    projectId: 'emergency-hub-e6079',
    authDomain: 'emergency-hub-e6079.firebaseapp.com',
    databaseURL: 'https://emergency-hub-e6079-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-hub-e6079.appspot.com',
    measurementId: 'G-DQZH6K75W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9j-I-xSNTuAFJto2CAkFl5pmIDOBS6EA',
    appId: '1:1098018897892:android:d5db6db23a7a37407751f1',
    messagingSenderId: '1098018897892',
    projectId: 'emergency-hub-e6079',
    databaseURL: 'https://emergency-hub-e6079-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-hub-e6079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYuydcajq9ANbyUhNn_HXtDajg0M337xk',
    appId: '1:1098018897892:ios:d05c2e7bfb029ee67751f1',
    messagingSenderId: '1098018897892',
    projectId: 'emergency-hub-e6079',
    databaseURL: 'https://emergency-hub-e6079-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-hub-e6079.appspot.com',
    iosBundleId: 'com.example.emergancyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYuydcajq9ANbyUhNn_HXtDajg0M337xk',
    appId: '1:1098018897892:ios:63711bae158b46027751f1',
    messagingSenderId: '1098018897892',
    projectId: 'emergency-hub-e6079',
    databaseURL: 'https://emergency-hub-e6079-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-hub-e6079.appspot.com',
    iosBundleId: 'com.example.emergancyhub.RunnerTests',
  );
}
